spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  cache:
    redis:
      time-to-live: 3600000
    type: redis

  data:
    redis:
      repositories:
        enabled: false
      url: ${REDIS_URL}

server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

logging:
  level:
    org.springframework.cache: TRACE

