spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesapp
    username: kirilkleinerman
    password:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

server:
  port: 8080

jwt:
  secret: cc0c8c3d81f69e4696825a447cab53ae5eaab65a198f6b1443fd0b32a0d9c75c
  expirationMs: 3600000 # 1 hour
